apiVersion: apps/v1
kind: Deployment
metadata:
  name: reserve-notice-db
  labels:
    app: reserve-notice-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reserve-notice-db
  template:
    metadata:
      labels:
        app: reserve-notice-db
    spec:
      containers:
      - name: reserve-notice-db
        image: postgres:11-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: m9amsa-configmap
        readinessProbe:
          exec:
            command:
            - psql
            - -U
            - postgres
            - -w
            - postgres
            - -c
            - "SELECT 1"
          initialDelaySeconds: 3
          periodSeconds: 3
