server:
  port: 28080
info:
  url:
    root-path: ${URL_ROOT}
flight-ticket-fare-calculation:
  ribbon:
    listOfServers: ${HOSTNAME_CALCULATE_FARE}
flight:
  ribbon:
    listOfServers: ${HOSTNAME_FLIGHT}
purchase:
  ribbon:
    listOfServers: ${HOSTNAME_PURCHASE}
logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
    com:
      example: INFO
      zaxxer: DEBUG
    root: ERROR
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint}
      %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint}
      [%16.16X{traceId}:%16.16X{parentSpanId}:%16.16X{spanId}] %clr(%-40.40logger{39}){cyan}
      %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
spring:
  application:
    name: reserve
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME_RESERVE}/m9amsa
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    kubernetes:
      ribbon:
        enabled: false
    stream:
      bindings:
        flight_input:
          destination: flight_topic
          contentType: application/json
        reservation_output:
          destination: reservation_topic
          contentType: application/json
      kafka:
        binder:
          brokers:
          - ${KAFKA_BROKER}
opentracing:
  jaeger:
    service-name: ${JAEGER_SERVICENAME_RESERVE}
    udp-sender:
      host: ${JAEGER_HOST}
      port: 6831
ribbon: # resilience4jのリトライタイムアウトを優先させるため、少し大きめの設定を行います。
  ConnectTimeout: 10000
  ReadTimeout: 10000
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 60000
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        record-failure-predicate: com.example.m9amsa.reserve.circuitbreaker.FeignClientExceptionPredicate
        register-health-indicator: true
    instances:
      calculateFareCircuitBreaker:
        baseConfig: default
      flightCircuitBreaker:
        baseConfig: default
      purchaseCircuitBreaker:
        baseConfig: default
      calculateFareCircuitBreakerForHealth:
        baseConfig: default
        sliding-window-size: 1
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 3000
      flightCircuitBreakerForHealth:
        baseConfig: default
        sliding-window-size: 1
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 3000
      purchaseCircuitBreakerForHealth:
        baseConfig: default
        sliding-window-size: 1
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 3000
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exception-predicate: com.example.m9amsa.reserve.circuitbreaker.FeignClientExceptionPredicate
    instances:
      calculateFareRetry:
        base-config: default
      flightRetry:
        base-config: default
      purchaseRetry:
        base-config: default
security:
  oauth2:
    resource:
      id: reserve-resource
      userInfoUri: http://${HOSTNAME_ACCOUNT}/${URL_ROOT}/account/auth/validateUser
    client:
      access-token-uri: http://${HOSTNAME_ACCOUNT}/auth/login
      client-id: ${OAUTH2_CLIENT_ID}
      client-secret: ${OAUTH2_CLIENT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
m9amsa:
  actuator:
    health:
      threshold:
        cpu: 0.8
        memory: 0.8