apiVersion: v1
kind: Service
metadata:
  name: purchase-notice
  labels:
    role: ${TARGET_ROLE}
spec:
  type: ClusterIP
  selector:
    app: purchase-notice
    role: ${TARGET_ROLE}
  ports:
  - port: 80
    targetPort: 28080
