server:
  port: 28080

info:
  url:
    root-path: ${URL_ROOT}

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME_ACCOUNT}/m9amsa
    username: postgres
    password: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: ConnectionPool
      leakDetectionThreshold: 5000
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
      idle-timeout: 10000
      max-lifetime: 30000
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
  cloud:
    kubernetes:
      ribbon:
        enabled: false

logging:
  level:
    org:
      springframework: INFO
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
    com:
      example: INFO
      zaxxer: DEBUG
    root: ERROR
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} [%16.16X{traceId}:%16.16X{parentSpanId}:%16.16X{spanId}] %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

opentracing:
  jaeger:
    service-name: ${JAEGER_SERVICENAME_ACCOUNT}
    udp-sender:
      host: ${JAEGER_HOST}
      port: 6831

management:
  endpoints:
    web:
      exposure:
        include: "*"