apiVersion: v1
kind: Service
metadata:
  name: flight-ticket-fare-calculation
  labels:
    role: ${TARGET_ROLE}
spec:
  type: ClusterIP
  selector:
    app: flight-ticket-fare-calculation
    role: ${TARGET_ROLE}
  ports:
  - port: 80
    targetPort: 28080